import { Card, Header } from "@/components";
import {
  LinkedIn,
  Github,
  Email,
  Javascript,
  ReactIcon,
  NextJS,
  TailwindIcon,
  NodeJS,
  Postgres,
  Redux,
  Arrow,
} from "@/icons";
import { Prisma } from "@/icons/prisma";
import { Typescript } from "@/icons/typescript";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import profilePic from "../assets/profile.png";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#16161A]">
        <Header />
        <div className="mb-12 grid max-w-[1220px] grid-cols-4 gap-4">
          <Card type="horizontal" className="col-span-2">
            <Image src={profilePic} alt="T3 Logo" width={100} height={100} />
            <p className="text-base text-[#fffffe]">
              Hey, I’m <span className="text-[#2cb67d]">Mohanad</span>, a
              developer and product designer from Egypt. I’m interested in
              React, Node, Product Design, Jamstack, Startups, Cryptocurrencies
              and Music.
            </p>
          </Card>
          <Card className="flex items-center justify-center">
            <div>
              <ul className="flex flex-wrap items-center justify-center gap-4">
                <li className="text-center">
                  <Javascript className="mx-auto h-10 w-10" />
                  <p className="text-sm text-[#fffffe]">Javascript</p>
                </li>
                <li className="text-center">
                  <Typescript className="mx-auto h-10 w-10" />
                  <p className="text-sm text-[#fffffe]">TypeScript</p>
                </li>
                <li className="text-center">
                  <ReactIcon className="mx-auto h-10 w-10" />
                  <p className="text-sm text-[#fffffe]">React</p>
                </li>
                <li className="text-center">
                  <Redux className="mx-auto h-10 w-10" />
                  <p className="text-sm text-[#fffffe]">Redux</p>
                </li>
                <li className="text-center">
                  <NextJS className="mx-auto h-10 w-10 text-white" />
                  <p className="text-sm text-[#fffffe]">Next JS</p>
                </li>
                <li className="text-center">
                  <TailwindIcon className="mx-auto h-10 w-10 text-white" />
                  <p className="text-sm text-[#fffffe]">Tailwind CSS</p>
                </li>
                <li className="text-center">
                  <Prisma className="mx-auto h-10 w-10 text-white" />
                  <p className="text-sm text-[#fffffe]">Prisma</p>
                </li>
                <li className="text-center">
                  <NodeJS className="mx-auto h-10 w-10 text-white" />
                  <p className="text-sm text-[#fffffe]">Node JS</p>
                </li>
                <li className="text-center">
                  <Postgres className="mx-auto h-10 w-10 text-white" />
                  <p className="text-sm text-[#fffffe]">PostgreSQL</p>
                </li>
              </ul>
            </div>
          </Card>
          <Card
            type="vertical"
            className="col-start-4 col-end-5 row-span-2"
          ></Card>
          <Card
            className="relative flex items-center justify-center"
            color="github"
          >
            <Github />
            <Link
              href=""
              className="absolute bottom-5 left-9 rounded-full bg-black/30 p-1.5"
            >
              <Arrow className="h-5 w-5" />
            </Link>
          </Card>
          <Card
            className="relative flex items-center justify-center"
            color="linkedin"
          >
            <LinkedIn className="h-24 w-24 text-white" />
            <Link
              href=""
              className="absolute bottom-5 left-9 rounded-full bg-black/30 p-1.5"
            >
              <Arrow className="h-5 w-5" />
            </Link>
          </Card>
          <Card className="flex items-center justify-center">
            <span className="text-2xl">Resume</span>
          </Card>
          <Card type="horizontal" className="col-span-2">
            <p className="text-lg font-semibold">Let’s connect</p>
            <input
              placeholder="Email address"
              className="w-full border-b-2 border-[#2CB67D] bg-transparent py-2.5 focus:outline-none"
            />
            <textarea
              placeholder="Message"
              className="w-full border-b-2 border-[#2CB67D] bg-transparent focus:outline-none"
            />
            <button className="mt-4 rounded-[36px] bg-[#2CB67D] py-1 px-5 text-[#fffffe]">
              Send
            </button>
          </Card>
          <Card type="horizontal" className="col-span-2"></Card>
          <Card type="squared" className=""></Card>
          <Card type="squared" className=""></Card>
          <Card type="squared" className=""></Card>
          <Card type="squared" className=""></Card>
        </div>
      </main>
    </>
  );
};

export default Home;
