import { Card, Header } from "@/components";
import { LinkedIn, Github, Email } from "@/icons";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../assets/profile.png";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#16161A]">
        <Header />
        <div className="mb-12 grid max-w-[1220px] grid-cols-4 gap-4">
          <Card type="horizontal" className="col-span-2">
            <Image src={profilePic} alt="T3 Logo" width={100} height={100} />
            <p className="text-base text-[#fffffe]">
              Hey, I’m <span className="text-[#2cb67d]">Mohanad</span>, a
              developer and product designer from Egypt. I’m interested in
              React, Node, Product Design, Jamstack, Startups, Cryptocurrencies
              and Music.
            </p>
          </Card>
          <Card className="flex items-center justify-center">
            <LinkedIn />
            <div className=""></div>
          </Card>
          <Card
            type="vertical"
            className="col-start-4 col-end-5 row-span-2"
          ></Card>
          <Card className="flex items-center justify-center">
            <Github />
          </Card>
          <Card className="flex items-center justify-center">
            <LinkedIn />
          </Card>
          <Card className="flex items-center justify-center">
            <LinkedIn />
          </Card>
          <Card type="horizontal" className="col-span-2">
            <p className="text-lg font-semibold">Let’s connect</p>
            <input
              placeholder="Email address"
              className="w-full border-b-2 border-[#2CB67D] bg-transparent py-2.5 focus:outline-none"
            />
            <textarea
              placeholder="Message"
              className="w-full border-b-2 border-[#2CB67D] bg-transparent focus:outline-none"
            />
            <button className="mt-4 rounded-[36px] bg-[#2CB67D] py-1 px-5 text-[#fffffe]">
              Send
            </button>
          </Card>
          <Card type="horizontal" className="col-span-2"></Card>
          <Card type="squared" className=""></Card>
          <Card type="squared" className=""></Card>
          <Card type="squared" className=""></Card>
          <Card type="squared" className=""></Card>
        </div>
      </main>
    </>
  );
};

export default Home;
